services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
        - "9999:8080"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "350MB"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true